"""Markdown output handler - exports debate to markdown file."""

from pathlib import Path
from typing import TYPE_CHECKING
from .base import OutputHandler

if TYPE_CHECKING:
    from ..config import DebateConfig
    from ..orchestrator import Turn, DebateResult


class MarkdownHandler(OutputHandler):
    """Exports debate transcript to markdown file."""

    def __init__(self, output_path: Path):
        """
        Initialize markdown handler.

        Args:
            output_path: Path to write markdown file
        """
        self.output_path = output_path
        self.content_lines = []

    def on_debate_start(self, config: "DebateConfig"):
        """Initialize markdown content with header."""
        self.content_lines = [
            f"# CLI Debate: {config.topic}",
            "",
            "## Configuration",
            "",
            f"- **Mode:** {config.mode}",
            f"- **Max Rounds:** {config.max_rounds}",
            f"- **Convergence Detection:** {'Enabled' if config.enable_convergence else 'Disabled'}",
        ]

        if config.enable_convergence:
            self.content_lines.append(f"- **Convergence Threshold:** {config.convergence_threshold}")

        self.content_lines.extend([
            "",
            "---",
            "",
            "## Debate Transcript",
            ""
        ])

    def on_turn_start(self, turn: "Turn"):
        """Markdown doesn't need turn start notification."""
        pass

    def on_turn_complete(self, turn: "Turn"):
        """Add turn to markdown content."""
        # Add round header if this is the first turn of the round
        self.content_lines.extend([
            f"### Round {turn.round_number}",
            "",
            f"#### {turn.cli_name.upper()}",
            ""
        ])

        # Add response
        if turn.success:
            self.content_lines.append(turn.response)
        else:
            self.content_lines.append(f"*[Error: Response failed or timed out]*")
            if turn.response:
                self.content_lines.append(f"\n{turn.response}")

        # Add metadata
        self.content_lines.extend([
            "",
            f"*Execution time: {turn.execution_time:.2f}s*",
            "",
            "---",
            ""
        ])

    def on_debate_complete(self, result: "DebateResult"):
        """Finalize and write markdown file."""
        # Add summary section
        self.content_lines.extend([
            "## Summary",
            "",
            f"- **Total Rounds:** {result.total_rounds}",
            f"- **End Reason:** {result.end_reason}",
        ])

        if result.converged:
            self.content_lines.extend([
                f"- **Convergence:** ✓ Yes",
                f"- **Convergence Reason:** {result.convergence_reason}",
            ])
        else:
            self.content_lines.append("- **Convergence:** ✗ No")

        # Calculate total execution time
        total_time = sum(turn.execution_time for turn in result.turns)
        self.content_lines.extend([
            "",
            f"**Total Execution Time:** {total_time:.2f}s",
            ""
        ])

        # Add footer
        from datetime import datetime
        self.content_lines.extend([
            "---",
            "",
            f"*Generated by CLI Debate Tool on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*",
        ])

        # Write to file
        self._write_file()

    def _write_file(self):
        """Write markdown content to file."""
        try:
            # Ensure parent directory exists
            self.output_path.parent.mkdir(parents=True, exist_ok=True)

            # Write content
            content = "\n".join(self.content_lines)
            self.output_path.write_text(content, encoding="utf-8")

            print(f"\n✓ Markdown transcript saved to: {self.output_path}")

        except Exception as e:
            print(f"\n✗ Failed to write markdown file: {e}")
